# Generated by Django 2.0.4 on 2018-12-13 08:56

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('data', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
            ],
        ),
    ]
