# Generated by Django 2.0.4 on 2018-12-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic_app', '0002_genericmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericmodel',
            old_name='name',
            new_name='general_name',
        ),
    ]
